testnet:
  DNS: AS12dCHtafNAiQMDFMoiyPqU1kX1S1Nn4PdAGvW9ffBueDW7JmLMP
  URLs:
    - http://81.49.155.238:33035
  Default: true

buildnet:
  DNS: AS1pzpVk79cubdM7Zk9pNdg1JR4qKooVa6usyquiCEQhPeRWD9k7
  URLs:
    - https://buildnet.massa.net/api/v2

labnet:
  DNS: AS1PV17jWkbUs7mfXsn8Xfs9AK6tHiJoxuGu7RySFMV8GYdMeUSh
  URLs:
    - 192.168.2.1
    - 192.168.2.2
